import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Amplify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen grid place-content-center">
        <h1 className="text-3xl font-bold">Hello world!</h1>
      </main>

      <footer className=""></footer>
    </div>
  );
};

export default Home;
